export const CHANGE_POSITION_ZOOM = "CHANGE_POSITION_ZOOM";

export const GET_SITES_BEGIN = "GET_SITES_BEGIN";
export const GET_SITES_SUCCESS = "GET_SITES_SUCCESS";
export const GET_SITES_ERROR = "GET_SITES_ERROR";

export const GET_SITE_BEGIN = "GET_SITE_BEGIN";
export const GET_SITE_SUCCESS = "GET_SITE_SUCCESS";
export const GET_SITE_ERROR = "GET_SITE_ERROR";

export const DISPLAY_INPUT_ALERT = "DISPLAY_INPUT_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const SET_FAVORITE = "SET_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";

export const FAV_SITE_BEGIN = "FAV_SITE_BEGIN";
export const FAV_SITE_SUCCESS = "FAV_SITE_SUCCESS";

export const UNFAV_SITE_BEGIN = "UNFAV_SITE_BEGIN";
export const UNFAV_SITE_SUCCESS = "UNFAV_SITE_SUCCESS";

export const GET_FAVS_BEGIN = "GET_FAVS_BEGIN";
export const GET_FAVS_SUCCESS = "GET_FAVS_SUCCESS";

export const HANDLE_SORT = "HANDLE_SORT";
export const CHANGE_PAGE = "CHANGE_PAGE";
